<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="base_oak">
  <!-- Macro base -->
  <xacro:macro name="base" params="camera_frame cam_pos_x cam_pos_y cam_pos_z cam_roll cam_pitch cam_yaw">
    <link name="base_oak">

      <visual>
        <origin xyz="0 0 0" rpy="1.56 0 -1.56"/>
        <geometry>
          <mesh filename="package://oak_d_camera/meshes/oak_dlite_base.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="1.56 0 -1.56"/>
        <geometry>
          <mesh filename="package://oak_d_camera/meshes/oak_dlite_base.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>

    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_oak"/>
      <child link="base_footprint"/>
      <origin xyz="0.055 0.015 -0.06863" rpy="0 0.0508 0"/>
    </joint>

    <link name="base_footprint">
        <inertial>
        <mass value="0.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
    </link>

    <joint name="footprint_oak_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="${camera_frame}"/>
      <origin xyz="${cam_pos_x} ${cam_pos_y} ${cam_pos_z + 0.08863}" rpy="${cam_roll} ${- 0.0508 - cam_pitch} ${cam_yaw}"/>
    </joint>

    <link name="${camera_frame}" />
  </xacro:macro>
</robot>
